ML01 Page styling task
kristsemils/ML-magento pull request #2
Opened 2024-12-19 10:24 UTC by kristsemils

2024-12-19 10:40 UTC, matiss-cudars requested changes

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
object manager is illegal.

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +$stockRegistry = $objectManager->get(\Magento\CatalogInventory\Api\StockRegistryInterface::class);
If you want to use some other classes that are not in this particular block, you need to create your own block. Possibly extending the block you are using right now, so you inherit all of the original block methods.
Then add methods you need like getStockItem etc.

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +/** @var Magento\Catalog\Block\Product\View $block */
import the classes

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +<form action="<?= $block->getAddToCartUrl($product) ?>" method="post">
need to escape url

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +            <button type="button" class="qty-btn" id="sub" data-bind="click: function() { subtract(); }">-</button>
it is better to use icons instead of "-" or "+", but for learning I will allow it. Next time use icons

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +            <input type="number" min="1" max="<?= $qty ?>" value="1" class="qty-input" id="qty" name="qty">
When you are echoing something in phtml, please use escapers. If escaper can't be used , use noEscape
like <?= /* @noEscape */ $yourVariable ?>

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +            <div class="product-stock-info"> <?= $product->isSalable() ? "IN STOCK" : "X OUT OF STOCK" ?>  </div>
missing escape
also all texts in phtml file need to be translated
like __('in stock')
Also use single quotes instead
And don't write text in uppercase. use css for making the text to uppercase if needed

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +                <div class="product-stock-qty"> <?= $qty ?> items available</div>
escape + translate

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +        <?= __('Add to Cart') ?>
escapeHtml

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/attributes.phtml
> +$catalogHelper = $this->helper('Magento\Catalog\Helper\Output');
this is not used

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/attributes.phtml
> +$displayAttributes = ['dimensions', 'color', 'material'];
better to create your own block class and define these in block

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/attributes.phtml
> +                <li><strong><?= $attribute->getFrontendLabel() ?>:</strong>
escape missing

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/attributes.phtml
> +                    <?= $attribute->getFrontend()->getValue($product) ?></li>
same here

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/attributes.phtml
> +        <?= $attributes['short_description']->getFrontend()->getValue($product) ?>
escape

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/related.phtml
> +    <div class="related-header">Related Products</div>
translate

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/related.phtml
> +/** @var Magento\Catalog\Block\Product\ProductList\Related $block */
import

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/related.phtml
> +                <img class="related-product-image" src="<?= $block->getImage($product, 'product_page_image_large')->getImageUrl() ?>" alt="<?= $product->getName() ?>" />
escape

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/related.phtml
> +                            <?= __('Add to Cart') ?>
escapers

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/upsell.phtml
> +/** @var Magento\Catalog\Block\Product\ProductList\Upsell $block */
import

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/upsell.phtml
> +        We found other products you might like!
translate

2024-12-19 10:40 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/upsell.phtml
> +            <a class="upsell-product-link" href="<?= $product->getProductUrl() ?>" >View Product</a>
escape

2024-12-23 09:19 UTC, matiss-cudars requested changes

2024-12-23 09:19 UTC, matiss-cudars commented on app/code/Magebit/Learning/Block/Product/View/AddToCart.php
> +use Magento\Framework\Registry;
I believe this is deprecated

2024-12-23 09:19 UTC, matiss-cudars commented on app/code/Magebit/Learning/Block/Product/View/AddToCart.php
> +class AddToCart extends Template
Better extend some block class from catalog 
something like vendor/magento/module-catalog/Block/Product/View.php
I can see that there are already methods for getting the product and url

2024-12-23 09:19 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> + * @var \Magento\Framework\Escaper $escaper
import

2024-12-23 09:19 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/addtocart.phtml
> +                <?= $product->isSaleable() ? $escaper->escapeHtml(__("IN STOCK")) : $escaper->escapeHtml(__("X OUT OF STOCK")) ?>
use lower case and make the text uppercase using css

2024-12-23 09:19 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/attributes.phtml
> +$displayAttributes = ['dimensions', 'color', 'material'];
Not resolved yet.
Create your own block to add to the functionality and use it here

2024-12-23 09:19 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/related.phtml
> +/** @var Magento\Catalog\Block\Product\ProductList\Related $block */
not resolved.

2024-12-23 09:19 UTC, matiss-cudars commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/upsell.phtml
> +/** @var Magento\Catalog\Block\Product\ProductList\Upsell $block */
not resolved

2025-01-02 09:57 UTC, RicardssbMagebit requested changes

2025-01-02 09:57 UTC, RicardssbMagebit commented on app/code/Magebit/Learning/Block/Product/View/AddToCart.php
> +        StringUtils $string,
private redonly should be used 

example:

private readonly  JsonEncoderInterface $jsonEncoder,

and removed from parent construct

2025-01-02 09:57 UTC, RicardssbMagebit commented on app/code/Magebit/Learning/Block/Product/View/AddToCart.php
> +        } catch (\Exception $e) {
Should be defined in use as use \Exception and here it should be Exception $e

2025-01-02 09:57 UTC, RicardssbMagebit commented on app/code/Magebit/Learning/Block/Product/View/ProductAttributes.php
> +        ConfigInterface $productTypeConfig,
again private redaonly

2025-01-02 09:57 UTC, RicardssbMagebit commented on app/code/Magebit/Learning/Block/Product/View/ProductAttributes.php
> +        \Magento\Catalog\Helper\Product $productHelper,
should be defined in use

2025-01-02 09:57 UTC, RicardssbMagebit commented on app/design/frontend/Magebit/Learning/Magento_Catalog/templates/product/view/attributes.phtml
> +            <p><?= /** @noEscape */ $shortDescription ?></p>
should use escaper if possible

2025-01-03 06:21 UTC, RicardssbMagebit approved these changes

2025-01-03 13:47 UTC, merged